workflow/core/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('workflow.core.views',

     (r'^logout/$', 'logout_view'),
     (r'^$', 'main'),
     (r'^main/$', 'main'),
     (r'^item/$', 'item'),
     (r'^item/get/$', 'get_item'),
     (r'^item/(?P<item_id>.+)/file/new/$', 'item_file'),
     (r'^item/(?P<item_id>.+)/file/(?P<file_name>.+)/$', 'item_file'),
     (r'^item/(?P<item_id>.+)/problem/new/$', 'problem_new'),
     (r'^item/(?P<item_id>.+)/$', 'item_detail'),
     (r'^problem/(?P<problem_id>.+)/$', 'problem_detail'),
     (r'^transaction/$', 'transaction'),
     (r'^reports/$', 'reports'),
     (r'^admin/$', 'admin'),
     (r'^sequence/$', 'sequence_list'),
     (r'^sequence/new/$', 'sequence_new'),
     (r'^sequence/(?P<sequence_id>.+)/$', 'sequence_detail'),
     (r'^batch/$', 'batch', {'view': 'active'}),
    # (r'^batch/all/$', 'batch', {'view': 'all'}),
     (r'^batch/new/$', 'batch_new'),
     (r'^batch/(?P<batch_name>.+)/change_status/$', 'batch_status_change'),
     (r'^batch/(?P<batch_id>.+)/change_active/$', 'batch_active_change'),
     (r'^batch/(?P<batch_name>.+)/add_items/$', 'batch_add_items'),
     (r'^batch/(?P<batch_name>.+)/add_item/$', 'batch_add_single_item'),
     (r'^batch/(?P<batch_name>.+)/(?P<new>.+)/$', 'batch_detail'),
     (r'^batch/(?P<batch_name>.+)/$', 'batch_detail'),
     (r'^collection/$', 'collection'),
     (r'^collection/(?P<collection_id>.+)/$', 'collection_detail'),
     (r'^property_owner/$', 'property_owner'),
     (r'^property_owner/(?P<property_owner_id>.+)/$', 'property_owner_detail'),
     (r'^item_type/$', 'item_type'),
     (r'^item_type/(?P<item_type_id>.+)/$', 'item_type_detail'),
     (r'^status/change/$', 'setup_status_change'),
     (r'^status/change/(?P<action>.+)/(?P<complete>.+)/$', 'status_change'),
     (r'^status/ready/(?P<action>.+)/$', 'status_ready'),
     (r'^transactions/$', 'transactions'),

)

workflow/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    # Uncomment this for admin:
    (r'^admin/', include(admin.site.urls)),
    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^workflow/', include('workflow.wflocal.urls')),
    (r'^core/', include('workflow.core.urls')),
)

workflow/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
import csv
import StringIO
#import django_filters

MIME_TYPE_CHOICES = (
    ('IMAGE_TIFF', 'image/tiff'),
    ('IMAGE_JPEG', 'image/jpeg'),
    ('IMAGE_JP2', 'image/jp2'),
    ('IMAGE_PNG', 'image/png'),
    ('IMAGE_GIF', 'image/gif'),
    ('TEXT_CSV', 'text/csv'),
    ('TEXT_HTML', 'text/html'),
    ('TEXT_XML', 'text/xml'),
    ('APPLICATION_ZIP', 'application/zip'),
    ('APPLICATION_PDF', 'application/pdf'),

)

FILE_USE_CHOICES = (
    ('MASTER', 'master'),
    ('TARGET', 'target'),
    ('THUMB', 'thumbnail'),
    ('MARCXML', 'MARCXML'),
    ('FGDC', 'FGDC'),
    ('KML', 'KML'),
    ('VRA_CORE', 'VRA Core'),
    ('MODS', 'MODS'),
    ('DC', 'Dublin Core'),
    ('PDF', 'PDF'),
    ('METS', 'METS'),
    ('EAD', 'EAD'),
    ('COPYRIGHTMD', 'copyrightMD'),
    ('THUMB', 'thumbnail'),
    ('OCR_ZIP', 'ocr - zipped'),
    ('OTHER', 'other'),
)
    

class WorkflowBatchFileCsv(forms.FileField):
    def clean(self, data, initial=None):
        """
        Check that the file uploaded contains properly formatted data, 
        i.e. csv-formatted records with at least a digital object indentifier and a
        title field.  The identifier must not already exist in the system.
        """
        super(forms.FileField, self).clean(initial or data)
        if not self.required:
            return None
        elif not data and initial:
            return initial
    
        # UploadedFile objects should have name and size attributes.
        try:
            file_name = data.name
            file_size = data.size
        except AttributeError:
            raise ValidationError(self.error_messages['invalid'])

        if not file_name:
            raise ValidationError(self.error_messages['invalid'])
        if not file_size:
            raise ValidationError(self.error_messages['empty'])

        conflicting_ids = []
        duplicate_ids = []
        seen_ids = {}
        destination = open('/tmp/' + data.name, 'wb+')
        for chunk in data.chunks():
            destination.write(chunk)
        destination.close()
        csv_data = csv.DictReader(open('/tmp/' + data.name))
        for line in csv_data:
            try:
                item_do_id = line['id']
                item_title = line['name'] 
            except Exception as e:
                raise forms.ValidationError('The file does not seem to be in the expected csv format.' + str(e))
            try: 
                Item.objects.get(do_id=item_do_id)
                conflicting_ids.append(item_do_id)
            except Item.DoesNotExist:
                pass
            try: 
                seen_ids[item_do_id]
                duplicate_ids.append(item_do_id)
            except:
                seen_ids[item_do_id] = 1
        if len(conflicting_ids) > 0:
            raise forms.ValidationError('Items in the data file conflict with existing item identifiers: ' + ', '.join(conflicting_ids))    
        if len(duplicate_ids) > 0:
            raise forms.ValidationError('Items in the data file include duplicate item identifiers: ' + ', '.join(duplicate_ids))
        
        return data

class Collection(models.Model):
    c_id = models.CharField(max_length=64, unique=True)
    name = models.CharField(max_length=255)
    def __unicode__(self):
        return self.c_id
    def get_ready_actions(self):
        """Gets list of actions for which items in this collection are ready.  Each actions has a numbered count attribute."""
        ready_actions = []
        distinct_actions = Item_Current_Status.objects.filter(item__collection_item__collection=self).values('ready_action').distinct()
        for a in distinct_actions:
            if not a['ready_action']:
                continue
            act = Action.objects.get(id=a['ready_action'])
            act.count = Item_Current_Status.objects.filter(item__collection_item__collection=self, ready_action=act).count()
            ready_actions.append(act)
        return ready_actions
    def get_item_actions(self):
        actions = []
        distinct_actions = Item_Actions_Status.objects.filter(item__collection_item__collection=self).values('action').distinct()
        for a in distinct_actions:
            if not a['action']:
                continue
            act = Action.objects.get(id=a['action'])
            act.count = Item_Actions_Status.objects.filter(item__collection_item__collection=self, action=act).count()
            act.count_complete = Item_Actions_Status.objects.filter(item__collection_item__collection=self, action=act, complete=True).count()
            act.count_ready = Item_Actions_Status.objects.filter(item__collection_item__collection=self, action=act, ready=True).count()
            actions.append(act)
        return actions
    def get_problem_item_count(self):
        """Gets count of items in this batch that have unresolved problems"""
        return Item_Current_Status.objects.filter(item__collection_item__collection=self, has_problem=True).count() 



# Actions that can be required by items
class Action(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField()
    def __unicode__(self):
        return self.name

class Item_Type(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField()
    def __unicode__(self):
        return self.name

class Property_Owner(models.Model):
    name = models.CharField(max_length=64)
    depositor = models.CharField(max_length=255)
    description = models.TextField()
    def __unicode__(self):
        return self.description

class Workflow_Sequence(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True, null=True)
    actions = models.ManyToManyField(Action, through='Workflow_Sequence_Actions', blank=True, null=True)
    def __unicode__(self):
        return self.name
    def get_ordered_actions(self):
        return Workflow_Sequence_Actions.objects.filter(workflow_sequence=self).order_by('order')

class Workflow_Sequence_Actions(models.Model):
    workflow_sequence = models.ForeignKey(Workflow_Sequence)
    action = models.ForeignKey(Action)
    order = models.IntegerField()

# suggested id value is combination of collection id and date
class Batch(models.Model):
    name = models.CharField(max_length=64, unique=True)
    collection = models.ForeignKey(Collection)
    type = models.ForeignKey(Item_Type)
    property_owner = models.ForeignKey(Property_Owner, blank=True, null=True)
    description = models.TextField(blank=True)
    sequence = models.ForeignKey(Workflow_Sequence)
    item_count = models.IntegerField(blank=True, null=True, editable=False, default=0)
    date = models.DateField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return '%s [%s]' % (self.name, self.collection.c_id)

    def get_ready_actions(self):
        """Gets list of actions for which items in this batch are ready.  Each actions has a numbered count attribute."""
        ready_actions = []
        distinct_actions = Item_Current_Status.objects.filter(item__batch_item__batch=self).values('ready_action').distinct()
        for a in distinct_actions:
            if not a['ready_action']:
                continue
            act = Action.objects.get(id=a['ready_action'])
            act.count = Item_Current_Status.objects.filter(item__batch_item__batch=self, ready_action=act).count()
            ready_actions.append(act)
        return ready_actions
    def get_item_actions(self):
        actions = []
        distinct_actions = Item_Actions_Status.objects.filter(item__batch_item__batch=self).values('action').distinct()
        for a in distinct_actions:
            if not a['action']:
                continue
            act = Action.objects.get(id=a['action'])
            act.count = Item_Actions_Status.objects.filter(item__batch_item__batch=self, action=act).count()
            act.count_complete = Item_Actions_Status.objects.filter(item__batch_item__batch=self, action=act, complete=True).count()
            act.count_ready = Item_Actions_Status.objects.filter(item__batch_item__batch=self, action=act, ready=True).count()
            actions.append(act)
        return actions
    def get_problem_item_count(self):
        """Gets count of items in this batch that have unresolved problems"""
        return Item_Current_Status.objects.filter(item__batch_item__batch=self, has_problem=True).count() 


class Item(models.Model):
    do_id = models.CharField('identifier', max_length=64, unique=True)
    name = models.CharField(max_length=255)
    type = models.ForeignKey(Item_Type)
    property_owner = models.ForeignKey(Property_Owner, blank=True, null=True)
    primary_collection = models.ForeignKey(Collection)
    def __unicode__(self):
        return self.name

    def inherit_from_batch(self, batch, clobber=False):
        if clobber or not self.type_id:
            self.type = batch.type
        if clobber or not self.property_owner:
            self.property_owner = batch.property_owner
        if clobber or not self.primary_collection_id:
            self.primary_collection = batch.collection

    def ready_action(self):
        ics = Item_Current_Status.objects.get(item=self)
        return ics.ready_action

    def set_action_complete(self, action, complete='True'):
        ias = self.item_actions_status_set.get(action=action)
        if complete == 'True':
            if (not ias.ready):
                raise Exception('item %s is not ready to have action %s completed.' % (self.do_id, action.name,))
            ias.complete = True
            ias.ready = False
            ias.save()
        elif complete == 'False':
            if (not ias.complete):
                return
            ias.complete = False
            ias.ready = True
            ias.save()

templates/core/add_single_item_to_batch.html
{% extends "core/base.html" %}

{% block content %}

<div id="pageTitle">workflow &gt; <a href="{% url core.views.main %}">main menu</a> &gt; <a href="/django/workflow/batch">batch</a> &gt; <a href="/django/workflow/batch/{{ batch.name }}">{{ batch.name }}</a> &gt; add item</div>  
{% if form.errors %}<div class="ui-state-error ui-corner-all" style="padding: 0pt 0.7em;"><p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"></span>{{ form.errors }}</p></div>{% endif %}

<form enctype="multipart/form-data"  method="POST">
<table class="form" cellspacing="5" cellpadding="5">
<tr><td><label name="">batch identifier</label></td><td>{{ batch.name }}</td></tr>
<tr><td><label name="">collection:</label></td><td>{{ batch.collection.c_id }}</td></tr>
<tr><td><label name="">notes / description</label></td><td>{{ batch.description }}</td></tr>
{{ item_form }}
<tr><td colspan="2">
<input type="submit" class="medium" value="save and add another" name="_addanother"/>
<input type="submit" class="medium" value="save and return to batch" name="_return"/></td></tr>
</table>
</form>
{% endblock %}

templates/core/add_to_batch.html
{% extends "core/base.html" %}

{% block content %}

<div id="pageTitle">workflow &gt; <a href="{% url core.views.main %}">main menu</a> &gt; <a href="/django/workflow/batch">batch</a> &gt; <a href="/django/workflow/batch/{{ batch.name }}">{{ batch.name }}</a> &gt; add items</div>  
{% if form.errors %}<div class="ui-state-error ui-corner-all" style="padding: 0pt 0.7em;"><p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"></span>{{ form.errors }}</p></div>{% endif %}

<form enctype="multipart/form-data"  method="POST">
<table class="form" cellspacing="5" cellpadding="5">
<tr><td><label name="">batch identifier</label></td><td>{{ batch.name }}</td></tr>
<tr><td><label name="">collection:</label></td><td>{{ batch.collection.c_id }}</td></tr>
<tr><td><label name="">content type:</label></td><td>{{ batch.type.name }}</td></tr>
<tr><td><label name="">property owner</label></td><td>{{ batch.property_owner.name }}</td></tr>
<tr><td><label name="">notes / description</label></td><td>{{ batch.description }}</td></tr>
<tr><td><label name="">items</label></td><td>{{ batch.item_count }}</td></tr>
<tr><td><label name="">sequence of actions</label></td><td>{{ batch.sequence }}</td></tr>
{% if form.file.errors %}<tr><td colspan="2"><div class="ui-widget"><div class="ui-state-error ui-corner-all" style="padding: 0pt 0.7em;"><p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"></span>{{ form.file.errors }}</p></div></div></td></tr>{% endif %}
<tr><td><label name="">upload item records<br />(csv text):</label></td><td>{{ form.file }}</td></tr>
<tr><td colspan="2">
<input type="hidden" name="name" id="id_name" value="{{ batch.name }}" />
<input type="hidden" name="collection" id="id_collection" value="{{ batch.collection.id }}" />
<input type="hidden" name="property_owner" id="id_property_owner" value="{{ batch.property_owner.id }}" />
<input type="hidden" name="type" id="id_type" value="{{ batch.type.id }}" />
<input type="hidden" name="description" id="id_description" value="none" />
<input type="hidden" name="sequence" id="id_sequence" value="{{ batch.sequence.id }}" />
<input type="submit" id="id_submit" value="add items to batch" /></td></tr>
</form>
</table>
{% endblock %}

templates/core/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}drl workflow{% endblock %}</title>
     <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/workflow2.css" />
     <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}jquery/jquery-ui.custom.css" />
     <script type="text/javascript" src="{{ MEDIA_URL }}jquery/jquery.js"></script>
     <script type="text/javascript" src="{{ MEDIA_URL }}jquery/jquery-ui.js"></script>


 <script type="text/javascript">
    
    {% include "core/main.js" %}

	$(function() {
	
	    $("input:first").focus();
		$("#tabs").tabs();


	});
	</script>

</head>

<body>

    <div id="container">
  {% if user.first_name %}
       <p class="small">you are logged in as <span class="ui-state-highlight hilight">{{ user.first_name }}</span> &gt; <a href="{% url core.views.logout_view %}">logout</a></p>
  {% endif %}
      {% block content %}{% endblock %}
    </div>
      
  {% if user.first_name %}
    <div id="footer">
        <p class="small">you are logged in as <span class="ui-state-highlight hilight">{{ user.first_name }}</span> &gt; <a href="{% url core.views.logout_view %}">logout</a></p>
    </div>
  {% endif %}

</body>
</html>

templates/core/collection_detail.html
{% extends "core/base.html" %}

{% block content %}

{% load core_extras %}


 <div id="newSearch"><form name="form" method="get" action="{% url core.views.get_item %}">look up an item by id: <input type="text" name="q" size="14" /><input type="hidden" name="lookup" value="identifier"> &nbsp; <button type="submit" class="tiny">go</button></form> </div>

<div id="pageTitle">workflow &gt; <a href="{% url core.views.main %}">main menu</a> &gt; <a href="/django/workflow/collection/">collection</a> &gt; {{ collection.c_id }}</div>  



<div id="facets">
<p><b>filter results:</b></p>
  <p>batches</p>
      <ul>
     {% for b in c_batches %}
		<li><a href="/django/workflow/batch/{{ b.name }}/">{{ b.name }}</a></li>
      {% endfor %}
	 </ul>
  <p>ready for:</p>
      <ul>
     {% for a in action_facet %}
     {% if a.count_ready  %}<li><a href="?&ready_action={{ a.id }}">{{ a.name }} ({{ a.count_ready }})</a></li>{% endif %}
      {% endfor %}
      {% if request.GET.ready_action %}
      <a href="?ready_action=">[all actions]</a>
      {% endif %}
      </ul>

  <p>problems:</p>
      <ul>
     {% if problem_facet %}
     <li><a href="?&has_problem=True">{{ problem_facet }} items</a></li>
      {% if request.GET.has_problem %}
      <a href="?last_action=">[clear]</a>
      {% endif %}
	  {% else %}
		<li>no problems</li>
	  {% endif %}
      </ul>
</div>

<div id="body_content">
<h3>{{ collection.name }}</h3>
<p><b>description:</b> {{ collection.description }}</p>
		 
<p>{{ c_count }} items in this collection - showing {{ items.start_index }} - {{ items.end_index }} {% include "core/pager_nav.html" %}
<table border="0" cellpadding="8" class="striped">
<thead>
  <tr>
<th> </th>
<th>files</th>
  </tr>
</thead>
{% for item in items.object_list %}
<tr{% if item.item.has_problem %} class="ui-state-error"{% endif %}>
<td><input type="checkbox" name="checked" value="{{ item.item.do_id }}" /></td>
<td><a href="/django/workflow/item/{{ item.item.do_id }}">{{ item.item.do_id }}</a></td>
<td width="350">{{ item.item.name }}{{ item.item.item_file.name }}</td>

    <td {% if item.ready_action %}class="action ready"{% endif %} id="{{ item.do_id }}_{{ item.ready_action.id }}" item="{{ item.item.do_id }}" action="{{ item.ready_action.id }}">{{ item.ready_action|default:"-" }}</td>
    <td>{{ item.last_transaction.description|default:"-" }} </td>
    <td>{{ item.last_transaction.timestamp|default:"-" }} </td>
    <td>{{ item.last_transaction.user.first_name|default:"-" }} </td>
	<td>{{ item.first_file }}{% if item.file_count %}... [{{ item.file_count }} total]{% endif %}</td>

</tr>
{% endfor %}
</table>
{% include "core/pager_nav.html" %}
</div>


<div id="reset_dialog" class="hidden" title="reset">reset this and all following actions to "incomplete"?</div>
<div id="action_dialog" class="hidden" title="record work">complete this action or log progress:</div>

{% endblock %}

templates/core/item_file.html
{% extends "core/base.html" %}

{% block content %}




<div id="pageTitle">workflow &gt; <a href="{% url core.views.main %}">main menu</a> &gt; <a href="/django/workflow/item/{{ item }}/">{{ item }}</a> &gt; file</div>  

<form method="POST">
<table class="form" cellspacing="5">

{{ form }}
<tr><td><input type="submit" /></td></tr>
</table>
</form>



{% endblock %}

templates/core/newbatch.html
{% extends "core/base.html" %}

{% block content %}

	<script type="text/javascript">
	$(function() {
	
		$("#id_collection").change( function () { 
		    date = new Date();
		    var month = (date.getMonth() + 1);
		    if (month < 10) { 
		        month = "0" + month.toString(); 
		    } else { 
		        month = month.toString(); 
		    }
		    var day = date.getDate()
   		    if (day < 10) { 
   		        day = "0" + day.toString(); 
   		    } else { 
   		        day = day.toString(); 
   		    }
		    var tstamp = date.getFullYear().toString() + month + day;  
            $("#id_name").val(tstamp + "-" + $("#id_collection").val());
        });

	});
	</script>


<div id="pageTitle">workflow &gt; <a href="{% url core.views.main %}">main menu</a> &gt; <a href="/django/workflow/admin">admin</a> &gt; new batch</div>  

<form enctype="multipart/form-data"  method="POST">
<table class="form" cellspacing="5" cellpadding="5">
{{ form }}
<tr><td colspan="2"><input type="submit" id="id_submit" value="create batch" /></td></tr>
</form>
</table>
<div id="actions_display"></div>
{% endblock %}

templates/core/reports.html
{% extends "core/base.html" %}

{% block content %}
<div id="pageTitle">drl workflow &gt; <a href="{% url core.views.main %}">main menu</a> &gt; reports</div>

<p>
	<h3>heading:</h3>
	<ul>
	<li><a href="">a report</a></li>
	<li><a href="">a report</a></li>

	
</p>

{% endblock %}

templates/core/sequence.html
{% extends "core/base.html" %}

{% block content %}

	<script type="text/javascript">
	$(function() {
	
		$('#add_action').click( function () {
			var n = parseInt($('#actions_table tr:last-child td:first').text()) + 1;
			$('#actions_table').append('<tr><td>' + n + '</td><td><select>{% for a in actions %}<option value="{{ a.id }}">{{ a }}</option>{% endfor %}</select></td></tr>');
		});

		$('#remove_action').click( function () {
			$('#actions_table tr:last-child').remove();
		});

		$('form').submit( function () {
			var actions_arr = [];
			$("select", "#actions_table").each(function () {
				var v = $(this).val();
				actions_arr.push(v);
			});
			var actions_string = actions_arr.join(',');
			$("#id_actions").val(actions_string);
		});
	});
	</script>


<div id="pageTitle">workflow &gt; <a href="{% url core.views.main %}">main menu</a> &gt; <a href="/django/workflow/admin">admin</a> &gt; <a href="/django/workflow/sequence/">sequence</a> &gt; {{ sequence.name }}</div>  

<form method="POST">
<table class="form" cellspacing="5" cellpadding="5">
    {% if workflow_sequence_form.name.errors %}
        <tr>
            <td colspan="2">
                <div class="ui-widget">
                    <div class="ui-state-error ui-corner-all" style="padding: 0pt 0.7em;">
                        <p>
                            <span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"></span>
                            {{ workflow_sequence_form.name.errors }}
                        </p>
                    </div>
                </div>
            </td>
        </tr>
    {% endif %}
<tr><td><label name="">workflow sequence name</label></td><td>{{ workflow_sequence_form.name }}</td></tr>
{% if workflow_sequence_form.description.errors %}<tr><td colspan="2"><div class="ui-widget"><div class="ui-state-error ui-corner-all" style="padding: 0pt 0.7em;"><p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"></span>{{ workflow_sequence_form.description.errors }}</p></div></div></td></tr>{% endif %}
<tr><td><label name="">notes / description (optional)</label></td><td>{{ workflow_sequence_form.description }}</td></tr>
{% if workflow_sequence_form.actions.errors %}<tr><td colspan="2"><div class="ui-widget"><div class="ui-state-error ui-corner-all" style="padding: 0pt 0.7em;"><p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"></span>{{ workflow_sequence_form.actions.errors }}</p></div></div></td></tr>{% endif %}
{% if seq_actions %}
<tr><td> </td><td><div class="ui-widget"><div class="ui-state-error ui-corner-all" style="padding: 0pt 0.7em;"><p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: 0.3em;"></span>NOTE: changing or updating sequence actions here will NOT affect any workflow items that already exist.</p></div></div></td></tr>
{% endif %}
<tr><td>actions</td>
<td bgcolor="#EFDFDF">
<table id="actions_table" cellpadding="6">
<tr><th>order</th><th>action</th></tr>
{% if seq_actions %}
	{% for s_a in seq_actions %}
	<tr>
        <td>{{ s_a.order }}</td>
        <td><select name="actions">{% for a in actions %}<option value="{{ a.id }}"{% ifequal s_a.action.name a.name %} selected="yes"{% endifequal %}>{{ a }}</option>{% endfor %}</select></td>
    </tr>
	{% endfor %}
	</table>
    <a href="#" id="add_action">add another action</a> | <a href="#" id="remove_action">remove last action</a>
    </td>
</tr>
<tr><td colspan="2">{{ workflow_sequence_form.this_id }}{{ workflow_sequence_form.actions }}<input type="submit" size="+2" id="id_submit" value="update workflow_sequence" /></td></tr>
{% else %}
<tr><td>1</td><td><select name="actions">{% for a in actions %}<option value="{{ a.id }}">{{ a }}</option>{% endfor %}</select></td></tr>
</table>
<a href="#" id="add_action">add another action</a> | <a href="#" id="remove_action">remove last action</a>
</td></tr>
<tr><td colspan="2">{{ workflow_sequence_form.actions }}<input type="submit" class="medium" id="id_submit" value="create sequence" /></td></tr>
{% endif %}
</table>
</form>
<div id="actions_display"></div>
{% endblock %}

templates/core/status_change.html
{% extends "core/base.html" %}

{% block content %}


<div id="pageTitle">workflow &gt; <a href="{% url core.views.main %}">main menu</a> &gt; <a href="/django/workflow/admin/">admin</a> &gt; <a href="/django/workflow/status/change/">quick status change</a> &gt; set {{ action }} to <i>{% ifequal complete "True" %}complete{% else %}incomplete{% endifequal %}</i></div>  

<form method="POST">
<table>

{{ form }}
</table>
<input type="hidden" name="user" value="{{ user.id }}" />
<p><input type="submit" value="submit" /></p>
</form>

{% endblock %}